**DATA IMPORTATION**




In [ ]:
import numpy as np
import pandas as pd


df= pd.read_csv ('football_players.csv', encoding = 'latin-1')

In [ ]:
df.head()

Name  Age Nationality  Overall  Acceleration  Aggression  \
0  Cristiano Ronaldo   32    Portugal     94.0          89.0        63.0   
1           L. Messi   30   Argentina     93.0          92.0        48.0   
2             Neymar   25      Brazil     92.0          94.0        56.0   
3          L. Suárez   30     Uruguay     92.0          88.0        78.0   
4           M. Neuer   31     Germany     92.0          58.0        29.0   

   Agility  Balance  Ball control  Composure  ...  Shot power  Sliding tackle  \
0     89.0     63.0          93.0       95.0  ...        94.0            23.0   
1     90.0     95.0          95.0       96.0  ...        85.0            26.0   
2     96.0     82.0          95.0       92.0  ...        80.0            33.0   
3     86.0     60.0          91.0       83.0  ...        87.0            38.0   
4     52.0     35.0          48.0       70.0  ...        25.0            11.0   

   Sprint speed  Stamina  Standing tackle  Strength  Vision  Volleys  \
0          91.0     92.0             31.0      80.0    85.0     88.0   
1          87.0     73.0             28.0      59.0    90.0     85.0   
2          90.0     78.0             24.0      53.0    80.0     83.0   
3          77.0     89.0             45.0      80.0    84.0     88.0   
4          61.0     44.0             10.0      83.0    70.0     11.0   

   Preferred Positions  Preferred Positions Type  
0               ST LW                    Forward  
1                  RW                    Forward  
2                  LW                    Forward  
3                  ST                    Forward  
4                  GK                 GoalKeeper  

[5 rows x 40 columns]

**DATA PROFILING**

In [ ]:
df.describe()

Age       Overall  Acceleration    Aggression       Agility  \
count  17981.000000  17981.000000  17981.000000  17981.000000  17981.000000   
mean      25.144541     66.247984     64.532618     55.789055     63.281464   
std        4.614272      6.987965     14.988620     17.485234     14.869227   
min       16.000000     46.000000     11.000000     11.000000     12.000000   
25%       21.000000     62.000000     56.000000     43.000000     55.000000   
50%       25.000000     66.000000     67.000000     59.000000     65.000000   
75%       28.000000     71.000000     75.000000     69.000000     74.000000   
max       47.000000     94.000000     96.000000     96.000000     96.000000   

            Balance  Ball control     Composure     Crossing         Curve  \
count  17981.000000  17981.000000  17981.000000  17981.00000  17981.000000   
mean      63.775596     58.004783     57.815472     49.71709     47.290028   
std       14.144136     16.887647     13.019767     18.48589     18.468629   
min       11.000000      8.000000      5.000000      5.00000      6.000000   
25%       56.000000     53.000000     51.000000     37.00000     34.000000   
50%       66.000000     63.000000     60.000000     54.00000     48.000000   
75%       74.000000     69.000000     67.000000     64.00000     62.000000   
max       96.000000     95.000000     96.000000     91.00000     92.000000   

       ...     Reactions  Short passing    Shot power  Sliding tackle  \
count  ...  17981.000000   17981.000000  17981.000000    17981.000000   
mean   ...     61.800178      58.203215     55.612980       45.504977   
std    ...      9.394082      15.018682     17.428851       21.486052   
min    ...     14.000000      10.000000      3.000000        4.000000   
25%    ...     55.000000      53.000000     46.000000       24.000000   
50%    ...     62.000000      62.000000     59.000000       51.000000   
75%    ...     68.000000      68.000000     69.000000       64.000000   
max    ...     96.000000      92.000000     94.000000       91.000000   

       Sprint speed       Stamina  Standing tackle      Strength  \
count  17981.000000  17981.000000     17981.000000  17981.000000   
mean      64.737501     63.166342        47.353874     65.202658   
std       14.743693     16.019221        21.838839     12.734994   
min       11.000000     12.000000         4.000000     12.000000   
25%       57.000000     56.000000        26.000000     58.000000   
50%       67.000000     66.000000        54.000000     66.000000   
75%       75.000000     74.000000        66.000000     74.000000   
max       96.000000     95.000000        92.000000     98.000000   

             Vision       Volleys  
count  17981.000000  17981.000000  
mean      52.955731     43.212725  
std       14.431258     17.742067  
min       10.000000      4.000000  
25%       43.000000     30.000000  
50%       54.000000     44.000000  
75%       64.000000     57.000000  
max       94.000000     91.000000  

[8 rows x 36 columns]

In [ ]:
#What is the most common Overall score for players in the database?

common_overall_rating = df['Overall'].mode()
print(common_overall_rating)

0    66.0
Name: Overall, dtype: float64


**DATA PREPROCESSING**

In [ ]:
cb =df[df['Preferred Positions'].str.contains('CB')]
cb ['Group'] = cb['Overall'].apply(lambda x: 'World class' if x >= 80 else ('Good' if 70 <= x <= 79 else 'Mediocre'))


<ipython-input-18-e9b893874807>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cb ['Group'] = cb['Overall'].apply(lambda x: 'World class' if x >= 80 else ('Good' if 70 <= x <= 79 else 'Mediocre'))


In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cb['Preferred Positions'] = le.fit_transform(cb['Preferred Positions'])
cb['Group'] = le.fit_transform(cb['Group'])
cb['Preferred Positions Type'] = le.fit_transform(cb['Preferred Positions Type'])
cb['Nationality'] = le.fit_transform(cb['Nationality'])


<ipython-input-32-85b6101da540>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cb['Preferred Positions'] = le.fit_transform(cb['Preferred Positions'])
<ipython-input-32-85b6101da540>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cb['Group'] = le.fit_transform(cb['Group'])
<ipython-input-32-85b6101da540>:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pand

**`DATA SPLITTING AND MODELLING WITH RANDOM FOREST**

In [ ]:
X = cb.drop(['Group'], axis=1)
y = cb['Group']

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Drop the 'Name' column from X before splitting into train and test sets.
X = cb.drop(['Group', 'Name'], axis=1)
y = cb['Group']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1971)

rf = RandomForestClassifier(n_estimators=500, random_state=1971)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_test)
coeff = rf.feature_importances_
coeff = pd.Series(coeff, index=X.columns)
coeff.sort_values(ascending=False)

Overall                     0.363894
Standing tackle             0.129729
Marking                     0.105171
Interceptions               0.080761
Sliding tackle              0.071991
Heading accuracy            0.046032
Reactions                   0.041396
Composure                   0.032370
Aggression                  0.019317
Short passing               0.016192
Ball control                0.013245
Long passing                0.009601
Strength                    0.008247
Shot power                  0.006309
Dribbling                   0.004570
Age                         0.004299
Vision                      0.003349
Crossing                    0.003056
Jumping                     0.002868
Stamina                     0.002620
Curve                       0.002614
Free kick accuracy          0.002599
Long shots                  0.002592
Penalties                   0.002497
Sprint speed                0.002396
Positioning                 0.002246
Acceleration                0.002139
Balance                     0.002073
Volleys                     0.002050
Finishing                   0.001937
Agility                     0.001883
Nationality                 0.001802
GK diving                   0.001474
GK handling                 0.001463
GK reflexes                 0.001336
GK kicking                  0.001251
GK positioning              0.001223
Preferred Positions         0.001123
Preferred Positions Type    0.000286
dtype: float64

MODEL EVALUATION

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


In [ ]:
confusion_mat = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{confusion_mat}")

Confusion Matrix:
[[244   0   0]
 [  0 467   0]
 [  0   0  15]]


In [ ]:
classification_report = classification_report(y_test, y_pred)
print(f"Classification Report:\n{classification_report}")

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       244
           1       1.00      1.00      1.00       467
           2       1.00      1.00      1.00        15

    accuracy                           1.00       726
   macro avg       1.00      1.00      1.00       726
weighted avg       1.00      1.00      1.00       726



PREDICTION WITH K-NEAREST NEIGHBOURS MODEL

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=911)

for n in range (1,6):
  print (f"n = {n}")
  knn = KNeighborsClassifier(n_neighbors=n)
  knn.fit(X_train, y_train)

  y_pred_knn = knn.predict(X_test)

  accuracy = accuracy_score(y_test, y_pred_knn)
  print(f"Accuracy: {accuracy}")
  f1_score_macro = f1_score(y_test, y_pred_knn, average='macro')
  print(f"f1 score (macro): {f1_score_macro}")

n = 1
Accuracy: 0.840567612687813
f1 score (macro): 0.709578288702489
n = 2
Accuracy: 0.8414023372287145
f1 score (macro): 0.649757926805604
n = 3
Accuracy: 0.8714524207011686
f1 score (macro): 0.708626497622317
n = 4
Accuracy: 0.8597662771285476
f1 score (macro): 0.6853476104856493
n = 5
Accuracy: 0.8739565943238731
f1 score (macro): 0.7153798863121333


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, f1_score
from sklearn.model_selection import train_test_split

# Assuming X and y are already defined as in your previous code

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=911)

best_f1_worldclass = 0
best_k_worldclass = 0
best_f1_good = 0
best_k_good = 0

for n in range(1, 6):
    print(f"n = {n}")
    knn = KNeighborsClassifier(n_neighbors=n)
    knn.fit(X_train, y_train)

    y_pred_knn = knn.predict(X_test)

    # Calculate F1-score for each class separately
    f1_scores = f1_score(y_test, y_pred_knn, average=None)

    # Assuming 'World Class' is the first class (index 0) and 'Good' is the second (index 1)
    f1_worldclass = f1_scores[0]
    f1_good = f1_scores[1]

    print(f"F1-score (World Class): {f1_worldclass}")
    print(f"F1-score (Good): {f1_good}")

    if f1_worldclass > best_f1_worldclass:
        best_f1_worldclass = f1_worldclass
        best_k_worldclass = n

    if f1_good > best_f1_good:
        best_f1_good = f1_good
        best_k_good = n

print("\nBest Results:")
print(f"Best k for World Class: {best_k_worldclass} with F1-score: {best_f1_worldclass}")
print(f"Best k for Good: {best_k_good} with F1-score: {best_f1_good}")

n = 1
F1-score (World Class): 0.728307254623044
F1-score (Good): 0.9004276114844226
n = 2
F1-score (World Class): 0.767726161369193
F1-score (Good): 0.8958333333333333
n = 3
F1-score (World Class): 0.7867036011080333
F1-score (Good): 0.9225092250922511
n = 4
F1-score (World Class): 0.7806788511749347
F1-score (Good): 0.9117276166456495
n = 5
F1-score (World Class): 0.7876230661040788
F1-score (Good): 0.9237339841366687

Best Results:
Best k for World Class: 5 with F1-score: 0.7876230661040788
Best k for Good: 5 with F1-score: 0.9237339841366687
